"""initial migration

Revision ID: 137dfc8f19bb
Revises: 
Create Date: 2025-06-06 16:31:02.903422

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '137dfc8f19bb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('hero', sa.Integer(), nullable=False),
    sa.Column('skin', sa.Integer(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('rank', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(length=300), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=36), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('coin', sa.Integer(), nullable=True),
    sa.Column('role', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('accs')
    # ### end Alembic commands ###
