"""Initial migration

Revision ID: 183a95922b25
Revises: 
Create Date: 2025-07-18 22:10:21.758961

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '183a95922b25'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accs', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['account_name'])

    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('acc_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('acc_pass', sa.String(length=100), nullable=True))
        batch_op.drop_constraint(batch_op.f('order_acc_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'accs', ['acc_id'], ['id'], ondelete='SET NULL')
        batch_op.drop_column('account_name')
        batch_op.drop_column('account_pass')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('account_pass', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('account_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('order_acc_id_fkey'), 'accs', ['acc_id'], ['id'])
        batch_op.drop_column('acc_pass')
        batch_op.drop_column('acc_name')

    with op.batch_alter_table('accs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
