"""add models Comments

Revision ID: 4b16af412d08
Revises: 183a95922b25
Create Date: 2025-07-29 21:18:15.056348

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b16af412d08'
down_revision = '183a95922b25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
